export const TYPES = {
  APP: {
    READY: 'APP.READY'
  },
  TIMER: {
    UPDATE: 'TIMER.UPDATE'
  },
  CONVERSATIONS: {
    NEW: 'CONVERSATIONS.NEW',
    REMOVE: 'CONVERSATIONS.REMOVE',
    ADD_BATCH: 'CONVERSATION.ADD_BATCH',
  },
  CONVERSATIONS_LIST: {
    ADD: 'CONVERSATIONS_LIST.ADD',
    ADD_BATCH: 'CONVERSATIONS_LIST.ADD_BATCH',
    SORT: 'CONVERSATIONS_LIST.SORT',
    REMOVE: 'CONVERSATIONS_LIST.REMOVE',
  },
  MESSAGE: {
    NEW: 'MESSAGE.NEW',
    ARCHIVE: 'MESSAGE.ARCHIVE',
    PENDING: 'MESSAGE.PENDING',
    SUBMIT: 'MESSAGE.SUBMIT',
    SUBMITED: 'MESSAGE.SUBMITED'
  },
  CONTACT: {
    NEW: 'CONTACT.NEW',
    CLICK: 'CONTACT.CLICK',
    SUBSCRIBED: 'CONTACT.SUBSCRIBED'
  }
};

export default TYPES;
