export const TYPES = {
  APP: {
    READY: 'APP.READY'
  },
  FETCH: {
    CLICK: 'FETCH.CLICK',
    FETCHING: 'FETCH.FETCHING',
    FETCHED: 'FETCH.FETCHED',
    ERROR: 'FETCH.ERROR',
  },
  TIMER: {
    UPDATE: 'TIMER.UPDATE'
  },
  MESSAGE: {
    NEW: 'MESSAGE.NEW',
    ARCHIVE: 'MESSAGE.ARCHIVE',
    PENDING: 'MESSAGE.PENDING',
    SUBMIT: 'MESSAGE.SUBMIT',
    SUBMITED: 'MESSAGE.SUBMITED'
  },
  CONTACT: {
    SUBSCRIBED: 'CONTACT.SUBSCRIBED',
    CLICK: 'CONTACT.CLICK'
  }
};

export default TYPES;
