export const TYPES = {
  APP: {
    READY: 'APP.READY'
  },
  FETCH: {
    CLICK: 'FETCH.CLICK',
    FETCHING: 'FETCH.FETCHING',
    FETCHED: 'FETCH.FETCHED',
    ERROR: 'FETCH.ERROR',
  },
  TIMER: {
    UPDATE: 'TIMER.UPDATE'
  },
  HEADLINE: {
    ARCHIVE: 'HEADLINE.ARCHIVE',
    NEW: 'HEADLINE.NEW',
    SUBMIT: 'HEADLINE.SUBMIT',
    SUBMITED: 'HEADLINE.SUBMITED'
  },
  PUBLISHER: {
    SUBSCRIBED: 'PUBLISHER.SUBSCRIBED',
    SUBSCRIPTION: {
      CLICK: 'PUBLISHER.SUBSCRIPTION.CLICK'
    }
  }
};

export default TYPES;
